# Generated by Django 5.2.8 on 2025-12-06 10:10

import acaciaapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acaciaapp', '0009_remove_ticket_reservation_ticket_reservation_booking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_number',
            field=models.CharField(default=acaciaapp.models.generate_ticket_number, editable=False, max_length=20, unique=True),
        ),
    ]
